services:
  # VPN Service
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped
    volumes:
      - ${ARRPATH}config/gluetun:/gluetun
    ports:
      # Common VPN Ports
      - "8888:8888/tcp" # HTTP proxy
      - "8388:8388/tcp" # Shadowsocks
      - "8388:8388/udp" # Shadowsocks
      # qBittorrent
      - "8081:8081"       # Web Interface
      - "6881:6881"       # TCP Port for Torrents
      - "6881:6881/udp"   # UDP Port for Torrents
      # Prowlarr
      - "9696:9696"       # Web Interface
      # FlareSolverr
      - "8191:8191"       # Web Interface
      # Sonarr
      - "8989:8989"       # Web Interface
      # Radarr
      - "7878:7878"       # Web Interface
      # Lidarr
      - "8686:8686"       # Web Interface
      # LazyLibrarian
      - "5299:5299"       # Web Interface
      # Bazarr
      - "6767:6767"       # Web Interface
      # Jellyseerr
      - "5055:5055"       # Web Interface
      # Jellyfin
      - "8096:8096/tcp"   # Web Interface
      - "7359:7359/udp"   # Auto Discovery
    env_file:
      - ./.env

  # Download Managers (Torrent)
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    restart: unless-stopped
    volumes:
      - ${ARRPATH}config/qbittorrent:/config
      - ${ARRPATH}data/downloads:/downloads
      - ${ARRPATH}data/movies:/data/movies
    environment:
      - WEBUI_PORT=8081
      - TORRENTING_PORT=6881
    env_file:
      - ./.env

  # Indexers
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "service:gluetun"
    restart: unless-stopped
    volumes:
      - ${ARRPATH}config/prowlarr:/config
      - ${ARRPATH}backup/prowlarr:/data/backup
      - ${ARRPATH}data/downloads:/downloads
    env_file:
      - ./.env

  # Captcha Solver
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: "service:gluetun"
    restart: unless-stopped
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    env_file:
      - ./.env

  # Media Management (Movies and Series)
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:gluetun"
    restart: unless-stopped
    volumes:
      - ${ARRPATH}config/sonarr:/config
      - ${ARRPATH}backup/sonarr:/data/backup
      - ${ARRPATH}data/tvshows:/data/tvshows
      - ${ARRPATH}data/downloads:/downloads
    env_file:
      - ./.env

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: "service:gluetun"
    restart: unless-stopped
    volumes:
      - ${ARRPATH}config/radarr:/config
      - ${ARRPATH}backup/radarr:/data/backup
      - ${ARRPATH}data/movies:/data/movies
      - ${ARRPATH}data/downloads:/downloads
    env_file:
      - ./.env
  
  # Music Management
  lidarr:
    image: ghcr.io/hotio/lidarr:latest
    container_name: lidarr
    network_mode: "service:gluetun"
    restart: unless-stopped
    volumes:
      - ${ARRPATH}config/lidarr:/config
      - ${ARRPATH}data/music:/data/music
      - ${ARRPATH}data/downloads:/downloads
    env_file:
      - ./.env
  
  # Book Management
  lazylibrarian:
    image: lscr.io/linuxserver/lazylibrarian:latest
    container_name: lazylibrarian
    environment:
      - DOCKER_MODS=linuxserver/mods:universal-calibre|linuxserver/mods:lazylibrarian-ffmpeg
    network_mode: "service:gluetun"
    restart: unless-stopped
    volumes:
      - ${ARRPATH}config/lazylibrarian/data:/config
      - ${ARRPATH}data/downloads:/downloads
      - ${ARRPATH}data/books:/books
    env_file:
      - ./.env

  # Subtitle Management
  bazarr:
    image: ghcr.io/hotio/bazarr:latest
    container_name: bazarr
    network_mode: "service:gluetun"
    restart: unless-stopped
    volumes:
      - ${ARRPATH}config/bazarr:/config
      - ${ARRPATH}data/movies:/data/movies
      - ${ARRPATH}data/tvshows:/data/tvshows
    env_file:
      - ./.env

  # Request Management
  # Unified Requests for Movies and TV Shows
  # Connects with Sonarr, Radarr, Lidarr, Readarr, and Jellyfin
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    network_mode: "service:gluetun"
    restart: unless-stopped
    volumes:
      - ${ARRPATH}config/jellyseerr:/app/config
    env_file:
      - ./.env

  # Multimedia Streaming Servers
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    network_mode: "service:gluetun"
    restart: unless-stopped
    volumes:
      - ${ARRPATH}config/jellyfin:/config
      - ${ARRPATH}data/movies:/data/movies
      - ${ARRPATH}data/tvshows:/data/tvshows
      - ${ARRPATH}data/downloads:/downloads
    env_file:
      - ./.env
